package modelo;
// Generated 5/02/2019 03:59:41 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idusuario;
     private String nombre;
     private String correo;
     private String contresenia;
     private Date fechanacimiento;

    public Usuario() {
    }

    public Usuario(int idusuario, String nombre, String correo, String contresenia, Date fechanacimiento) {
       this.idusuario = idusuario;
       this.nombre = nombre;
       this.correo = correo;
       this.contresenia = contresenia;
       this.fechanacimiento = fechanacimiento;
    }
   
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getContresenia() {
        return this.contresenia;
    }
    
    public void setContresenia(String contresenia) {
        this.contresenia = contresenia;
    }
    public Date getFechanacimiento() {
        return this.fechanacimiento;
    }
    
    public void setFechanacimiento(Date fechanacimiento) {
        this.fechanacimiento = fechanacimiento;
    }




}


